# Generated by Django 5.2 on 2025-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='fecha_ingreso',
            new_name='fechaAsignacion',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='fecha_ingreso',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='observacion',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='itv',
            old_name='aporte',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='hora_operacion_dia',
            new_name='horasOperacion',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='fecha_revision',
            new_name='ultimaRevision',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='gestion',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
    ]
