# Generated by Django 5.2 on 2025-05-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
