# Generated by Django 5.2 on 2025-06-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='maquinaria',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='maquinaria',
        ),
        migrations.RemoveField(
            model_name='itv',
            name='maquinaria',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='maquinaria',
        ),
        migrations.RemoveField(
            model_name='seguro',
            name='maquinaria',
        ),
        migrations.DeleteModel(
            name='Control',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Impuesto',
        ),
        migrations.DeleteModel(
            name='ITV',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.DeleteModel(
            name='Maquinaria',
        ),
        migrations.DeleteModel(
            name='Seguro',
        ),
    ]
