export const fieldLabels = {
  Maquinaria: [
    { name: 'placa', label: 'Placa' },
    { name: 'detalle', label: 'Descripción' },
    { name: 'unidad', label: 'Unidad' },
    { name: 'adqui', label: 'Adquisición' },
    { name: 'codigo', label: 'Código' },
    { name: 'tipo', label: 'Tipo' },
    { name: 'marca', label: 'Marca' },
    { name: 'modelo', label: 'Modelo' },
    { name: 'color', label: 'Color' },
    { name: 'metodo_depreciacion', label: 'Método de Depreciación' },
    { name: 'tipo_vehiculo', label: 'Tipo de Vehículo' },
    { name: 'crpva', label: 'CRPVA' },
    { name: 'nro_motor', label: 'Nro Motor' },
    { name: 'nro_chasis', label: 'Nro. Chasis' },
    { name: 'fecha_registro', label: 'Fecha Registro', type: 'date' },
    { name: 'registrado_por', label: 'Registrado por', readonly: true },
    { name: 'validado_por', label: 'Validado por', readonly: true },
    { name: 'autorizado_por', label: 'Autorizado por', readonly: true },
    { name: 'imagen', label: 'Imagen', type: 'file' },
  ],
  Control: [
    { name: 'fecha_inicio', label: 'Fecha de Inicio', type: 'date' },
    { name: 'fecha_final', label: 'Fecha Final', type: 'date' },
    { name: 'proyecto', label: 'Proyecto' },
    { name: 'ubicacion', label: 'Ubicación' },
    { name: 'estado', label: 'Estado'},
    { name: 'tiempo', label: 'Tiempo' },
    { name: 'operador', label: 'Operador' },
  ],
  'Asignación': [
    { name: 'unidad', label: 'Unidad', type: 'text' },
    { name: 'fecha_asignacion', label: 'Fecha de Asignación', type: 'date' },
    { name: 'kilometraje', label: 'Kilometraje', type: 'number' },
    { name: 'gerente', label: 'Gerente', type: 'text' },
    { name: 'encargado', label: 'Encargado', type: 'text' },
  ],
  'Liberación': [
    { name: 'unidad', label: 'Unidad', type: 'text' },
    { name: 'fecha_liberacion', label: 'Fecha de Liberación', type: 'date' },
    { name: 'kilometraje_entregado', label: 'Kilometraje Entregado', type: 'number' },
    { name: 'gerente', label: 'Gerente', type: 'text' },
    { name: 'encargado', label: 'Encargado', type: 'text' },
  ],
  Mantenimiento: [
    { name: 'tipo', label: 'Tipo' },
    { name: 'gestion', label: 'Gestión' },
    { name: 'lugarMantenimiento', label: 'Lugar de Mantenimiento' },
  ],
  Seguros: [
    { name: 'placa', label: 'Placa' },
    { name: 'numero2024', label: 'Número 2024' },
    { name: 'importeAsegurado2024', label: 'Importe Asegurado 2024', type: 'number' },
    { name: 'detalle', label: 'Detalle' },
  ],
  ITV: [
    { name: 'placa', label: 'Placa' },
    { name: 'detalle2024', label: 'Detalle 2024' },
    { name: 'importe2024', label: 'Importe 2024', type: 'number' },
  ],
  Impuestos: [
    { name: 'placa', label: 'Placa' },
    { name: 'importe2023', label: 'Importe 2023', type: 'number' },
    { name: 'importe2024', label: 'Importe 2024', type: 'number' },
  ],
  SOAT: [
    { name: 'placa', label: 'Placa' },
    { name: 'importe2024', label: 'Importe 2024', type: 'number' },
    { name: 'importe2025', label: 'Importe 2025', type: 'number' },
  ]
};
